### ISSUE TITLE
Voting: Map Marker Clustering

### ISSUE THREAD

**Issue by declandowling** [amay077/Xamarin.Forms.GoogleMaps#123] opened 2016-11-24 17:23 UTC
**If you want to this feature then post 👍  to below.**

### Suggestion

Implement google maps clustering utility for Android & iOS.

Android:
https://developers.google.com/maps/documentation/android-api/utility/marker-clustering

iOS:
https://developers.google.com/maps/documentation/ios-sdk/utility/marker-clustering

**Comment by amay077** [comment] 2016-12-03 07:01
Goog idea!
Is there someone who can port to C#?

**Comment by FWJay** [comment] 2016-12-06 14:56
this is a good place to start http://silverlightfoundry.blogspot.co.uk/2009/07/bing-maps-silverlight-control-part-5.html

**Comment by claudiocleberson** [comment] 2017-03-13 18:50
I stabled upon that repo, maybe that can help a bit with te Android side
https://github.com/oystehei/MapsUtilityDemo/tree/master/MapsUtilityDemo

**Comment by YahavGB** [comment] 2017-03-25 21:06
Someone found a way to integrate it? I can't find a way to translate Pin into POIItem.

**Comment by YahavGB** [comment] 2017-03-28 17:00
Okay, I'm working on a port to the clustering feature. I'll post it soon :).

**Comment by amay077** [comment] 2017-03-29 13:17
I found some repos.

* https://github.com/alexsorokoletov/Xamarin.Android.Maps.Utils
* https://github.com/sushihangover/XamarinGoogleMapClustering

But these are "Binding" projects.
I hope "PORT" from java to C# because core logic is same as Android and iOS.

**Comment by YahavGB** [comment] 2017-03-29 13:23
@amay077  yes, I mean a complete port to the clustering feature from Xamarin iOS and Xamarin Android to Xamarin Forms. This port is based on a fork of this project and its API, obviously.

**Comment by amay077** [comment] 2017-03-29 13:24
The original sources are here:

* https://github.com/googlemaps/android-maps-utils
* https://github.com/googlemaps/google-maps-ios-utils

Thanks @YahavGB, 
I am waiting expectantly.

**Comment by YahavGB** [comment] 2017-04-21 12:37
@amay077 as promised, I've implemented a unified API for clustering (a basic one, though).
The API supports marker clustering, custom markers, custom clusters and buckets. It currently works on iOS and Android.

Please check my forked repository and check it so I can submit a pull request - https://github.com/YahavGB/Xamarin.Forms.GoogleMaps.

Sample code:

            for (var i = 0; i <= ClusterItemsCount; i++)
            {
                var lat = this._currentPosition.Latitude + Extent * GetRandomNumber(-1.0, 1.0);
                var lng = this._currentPosition.Longitude + Extent * GetRandomNumber(-1.0, 1.0);

                this.Map.ClusteredPins.Add(new Pin()
                {
                    Position = new Position(lat, lng),
                    Label = $"Item {i}",
                    Icon = BitmapDescriptorFactory.FromBundle("pin_red.png")
                });
            }

Note the usage of ClusteredPins instead of Pins. Using that approach one can mix between standard pins (which won't be clustered) and clustered pins. For advance options, see ClusterOptions.cs.

Hope it'll help 👍 !

**Comment by mpghelli** [comment] 2017-04-28 10:52
Why don't incorporate that resource on the Xamarin.Forms.GoogleMaps package?

**Comment by YahavGB** [comment] 2017-04-28 10:56
@mpghelli The clustering feature has been implemented as a fork of this repository. When it'll get general approval I'll submit it as a pull request.
Meanwhile you can use my forked repository.

**Comment by amay077** [comment] 2017-04-28 11:03
I have a plan to contains Marker clustering in Xamarin.Forms.GoogleMaps.
But sorry I can not try @YahavGB 's implementation yet.

**Comment by mpghelli** [comment] 2017-04-28 11:09
Is there anyway to get forked repository by nuget? Im getting problems to compile Android and IOS project

**Comment by YahavGB** [comment] 2017-04-28 11:32
No, but I can upload the compiled dlls in case you'd like :)

ב-28 באפר׳ 2017, בשעה 14:09, ‏‏mpghelli ‏<notifications@github.com> כתב/ה:‬

**Comment by mpghelli** [comment] 2017-04-28 11:42
Yes. I Would like. I will be thankfull if you can do that to me.

**Comment by mpghelli** [comment] 2017-04-28 12:35
I did it compile and generated the Dlls. I've Added Xamarin.Forms.GoogleMaps dll reference on portable class library and Xamarin.Forms.GoogleMaps.Android too on Android project, but when i compile my project it throw some exceptions. Seems it lacks some packages of Android SDK itself:

Severity	Code	Description	Project	File	Line	Suppression State
Error		error: package com.google.maps.android.clustering.ClusterManager does not exist
		com.google.maps.android.clustering.ClusterManager.OnClusterClickListener	MRV.Terrenos.Mobile.Droid	C:\Projetos\MRV TERRENOS\src\v1\dev\MRVTerrenos\MRV.Terrenos.Mobile\MRV.Terrenos.Mobile.Droid\obj\Debug\android\src\mono\com\google\maps\android\clustering\ClusterManager_OnClusterClickListenerImplementor.java

I have to add any other references?

**Comment by YahavGB** [comment] 2017-04-28 14:09
@mpghelli I've uploaded the libraries to my Drive, you can grab them here: https://drive.google.com/drive/folders/0B02ufEMX6wJ7WmxFMHh2bHFXdUE?usp=sharing

How to integrate the libraries:

**The shared project**
_Instead of adding Xamarin.Forms.GoogleMaps from nuget_, add a reference to the local assembly you've downloaded from Drive.
<img width="621" alt="shared" src="https://cloud.githubusercontent.com/assets/1366751/25532239/5fdbf232-2c35-11e7-8751-d98739caa0b6.png">


**Android**
_Instead of adding the nuget package_, add a reference to these DLLs:
- Xamarin.Forms.GoogleMaps.dll
- Xamarin.Forms.GoogleMaps.Android.dll
- GoogleMapsUtility.dll
In addition, you do need to add a reference to Google Play Maps package, so you can do it using NuGet (simply install Xamarin.GooglePlayServices.Maps).
<img width="612" alt="Android"  src="https://cloud.githubusercontent.com/assets/1366751/25532194/21e4128e-2c35-11e7-8415-66fbf931c388.png">

**iOS**
_Instead of adding the nuget package_, add a reference to these DLLs:
- Xamarin.Forms.GoogleMaps.dll
- Xamarin.Forms.GoogleMaps.iOS.dll
- GoogleMapsUtility.dll
In addition, you do need to add a reference to Google Play Maps package, so you can do it using NuGet (simply install Xamarin.Google.iOS.Maps).
<img width="491" alt="iOS" src="https://cloud.githubusercontent.com/assets/1366751/25532208/34d4c654-2c35-11e7-8b20-4d9dd3ced810.png">

**Comment by YahavGB** [comment] 2017-04-28 14:11
@mpghelli It seems like it doesn't appear on the iOS image, but just to clarify, in the iOS project you should reference GoogleMapsUtils.iOS.dll.

**Comment by mpghelli** [comment] 2017-04-28 14:26
Thank you very much. I will try it and keep you informed. :)

**Comment by mpghelli** [comment] 2017-04-28 16:28
It Works!!!

But i don't understand some behaviors.  Some times it has just 5 pins, but group in a circle wrote with 10+. Is that the correct behavior?

Another question is if is possible to group the Pins with the same Icone first?

Thanks Again.

**Comment by YahavGB** [comment] 2017-04-28 16:39
Hi!

I'm glad that it works :).
Regarding the first question, it sounds incorrect. I did used buckets, so
it should group pins into groups (I don't remember the groups, you can find
them, and change them, in ClusterOptions.cs in the shared project), however
the described behavior sounds wrong.
Can you give me more details? Can you show me the code and tell in which
platform it occurs?

Regarding the second question, to the best of my knowledge the default
implementation doesn't do that and therefore we don't have that feature.
However, I wonder, maybe we can implement that manually by using multiple
cluster managers.

You welcome :).

**Comment by mpghelli** [comment] 2017-04-28 16:52
I have a collection that i  
loop through and create a clustered Pin for each one. I've tested only in android 5.0 until now.

foreach (var terreno in terrenos)
            {
                var pinCoord = GetPositionByCoordinate(terreno.Coordenadas.Split('|').First());

               var pin = CreateLandPin(
                   Terreno,
                   terreno.Id,
                   terreno.Nome,
                   terreno.Logradouro,
                   pinCoord,
                   terreno.Cor);

                  var customPin = new TerrenosPin(terreno, pin);
    
                this.mapTerrenos.ClusteredPins.Add(new Pin()
                {
                    Position = customPin.MapPinPosition,
                    Label = customPin.MapPinLabel,
                    Icon = customPin.MapPin.Icon
                });         
            }

Like i said, it groups less then 10 itens in a 10+ grouped pin, but when i clicked in that grouped pin it show the correct number of pins grouped inside.

Regards

**Comment by mpghelli** [comment] 2017-04-28 17:03
The CameraChanged event stoped worked in this dll version too.

Regards

**Comment by mpghelli** [comment] 2017-04-28 17:22
Another thing is if i have a polygon linked to the pin, i want to hide it too on grouping and not only the Pin.

Regards

**Comment by poseydonfba** [comment] 2017-05-04 23:07
I'm using the example: https://github.com/YahavGB/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/ClusterPage.xaml.cs

But with error in the line that adds the icon:
Icon = BitmapDescriptorFactory.FromBundle ("pin_red.png")


Any idea?


protected async override void OnAppearing()
        {
            base.OnAppearing();

            await LoadData();
        }

        public async Task LoadData()
        {
            this._currentPosition = await GetPosition();

            this.Map.MoveToRegion(MapSpan.FromCenterAndRadius(this._currentPosition, new Distance(100)), true);

            for (var i = 0; i <= ClusterItemsCount; i++)
            {
                var lat = this._currentPosition.Latitude + Extent * GetRandomNumber(-1.0, 1.0);
                var lng = this._currentPosition.Longitude + Extent * GetRandomNumber(-1.0, 1.0);

                this.Map.ClusteredPins.Add(new Pin()
                {
                    Position = new Position(lat, lng),
                    Label = $"Item {i}",
                    Icon = BitmapDescriptorFactory.FromBundle("pin_red.png")
                });
                this.Map.Pins.Add(new Pin()
                {
                    Position = new Position(lat, lng),
                    Label = $"Item {i}",
                    Icon = BitmapDescriptorFactory.FromBundle("pin_red.png")
                });
            }

            //this.Map.ClusterOptions.SetRenderUsingImage(BitmapDescriptorFactory.FromBundle("image01.png"));

            this.Map.Cluster();
        }

**Comment by poseydonfba** [comment] 2017-05-04 23:21
The icon shows grouped 10+, when I click on it, it shows 5 items in cluster, ... any ideas?

![image](https://cloud.githubusercontent.com/assets/9142662/25728719/30345318-3107-11e7-964c-bfec14bc2255.png)

**Comment by leaguefun** [comment] 2017-05-21 08:03
👍

**Comment by mpghelli** [comment] 2017-05-23 19:05
👍

**Comment by SimonTod** [comment] 2017-06-07 13:20
@YahavGB Just wanted to know if you made your pull request yet ?
I would really appreciate this feature. If you don't plan on making a pull request, maybe i will try doing it like @mpghelli did

**Comment by amay077** [comment] 2017-06-21 15:13
Hi @YahavGB, @bitbeans ,

Could you make marker clustering as other extension library (like a [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings)) ?

I hope keep simple this "core" Xamarin.Forms.GoogleMaps library.
But if you needed, I can make "internal visible" interface for extension library.

**Comment by gviddy** [comment] 2017-07-05 02:21
Yes it always shows 10+, even if I only have 5 pins... Is there a fix for this ?

**Comment by leaguefun** [comment] 2017-08-01 04:49
<img width="1523" alt="screen shot 2017-08-01 at 12 43 54 pm" src="https://user-images.githubusercontent.com/6715863/28809720-9f06b204-76b7-11e7-8364-4c579c6e88fe.png">

https://github.com/bitbeans/Xamarin.Forms.GoogleMaps/commit/4d27526c2847c84f19c948f2629adb3c7bcda7f5
I pull this branch and added back the missed ClusterPage, but the map object seems not adapted with this solution, please help, many thanks.

**Comment by mierzynskim** [comment] 2017-08-14 15:40
@gviddy @poseydonfba If you're still experiencing the problem with 10+ markers showing up, even if you have less than that, I think I've found a fix for that. Try to change **GetBucket** method implementation in **XamarinClusterRenderer** class:
```
protected override int GetBucket(ICluster cluster)
{
            int size = cluster.Size;
            if (size <= this._map.ClusterOptions.Buckets[0])
                return size;
            return this._map.ClusterOptions.Buckets[this.BucketIndexForSize(cluster.Size)];
}
```
Alternatively, you can add **ClusterOptions.RendererImage** or **ClusterOptions.RendererCallback**

**Comment by mortezabarzkar** [comment] 2017-09-13 11:56
can not find Com.Google.Maps.Android.Clustering in release mode !!!!!!!!!!!!!!!!!!!!!!

**Comment by ssotir** [comment] 2017-09-27 17:43
👍

**Comment by andreslon** [comment] 2017-09-29 03:40
@mierzynskim where is required to implement "GetBucket" for "the problem with 10+"

**Comment by mierzynskim** [comment] 2017-09-29 16:46
@andreslon **GetBucket** method is in **XamarinClusterRenderer** class. You can find it in @YahavGB fork here https://github.com/YahavGB/Xamarin.Forms.GoogleMaps

**Comment by xerx** [comment] 2018-04-24 12:33
@mierzynskim I have overriden the GetBucket method but when I build the android project I get an aapt.exe strange error

**Comment by vishaljani23** [comment] 2018-05-27 15:32
@amay077 It will be nice if it cane integrated with new updates....

**Comment by stavroaudi** [comment] 2018-07-24 12:00
Can you include it in release version? I'm having a hard time referencing @YahavGB's solution.

**Comment by KevinAble** [comment] 2018-07-24 20:16
@amay077  @YahavGB   This is a great feature,  we need it ASAP,   can it be integrated soon please?

**Comment by amay077** [comment] 2018-07-26 02:54
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/123#issuecomment-310110724

I hope someone makes "Marker Clustering" as extension library for Xamarin.Forms.GoogleMaps.
Of course I will help you if you needed.

**Comment by espritm** [comment] 2018-07-26 08:07
Same here, I'm trying to use YahavGB's library to get cluster..

**Comment by KevinAble** [comment] 2018-07-27 22:31
@amay077   I would be interested in your thoughts on making it an extension and how to do that architecturally,  
I was able to pull the latest version of the package and integrate what @YahavGB  had previously done for IOS (what I am only worried about for the moment).  I just have the projects in my solution and are referencing them directly.  
  There where a few things  that came out
- Rather than just dropping the GoogleMapsUtils.IOS DLL in I used the nuget package Xamarin.iOS.Maps.Utils
- The GMUClusterDelegateHandler  setting to the ClusterManager was taking over all the events (like camera idled),  I commented it out since it didn't do much, clustering still works and all the eventshandlers seem to firing fine.  (Took me a little bit to figure this one out)
-With the addition of the ClusterMarker type, the PIN lookup function in clusterlogic had to me modified to cast the Marker correctly for the LINQ to work,  the original ClusterMarker is stored in the userdata object on the event marker.  (I dont think the  TappedMarker functionality code worked in YahavGB's code) 
- There were also some casting checks that needed to be made in the UpdateSelectedPin methods in both PinLogic and ClusterLogic.  (Fairly obvious)

Hope this helps someone

**Comment by KevinAble** [comment] 2018-07-30 15:19
Sure, give me a few days I can make a branch for you.

**Comment by espritm** [comment] 2018-07-30 15:54
If you want to integrate @YahavGB 's code to enable Clustering, please use **ObservableRangeCollection** from [MVVM.Helper package nuget](https://github.com/jamesmontemagno/mvvm-helpers) instead of ObservableCollection or IList to store Clustered Pins.

It allows you to add as many pins as you want to the cluster, and once they are all added it calculates the cluster once : 
`
myMap.ClusteredPins.AddRange(lsMarkers); //calc and display cluster
`


Using an ObservableCollection force you to add pins one by one, and it calculates the cluster each time... more pins you have, more you app will freeze :/
```
foreach (var m in lsMarkers)

                    myMap.ClusteredPins.Add(m); //calc and display cluster
```
It happens in the class _Xamarin.Forms.GoogleMaps.Map_ when you will add a variable to store ClusteredPins
(to illustrate : https://github.com/YahavGB/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Map.cs line 165)

**Comment by stavroaudi** [comment] 2018-07-31 09:14
My problem with using @YahavGB's solution is that in my XAML I have 'InitialCameraUpdate' and now when I run my app I get MethodAccessException: Xamarin.Forms.GoogleMaps.Internals.CameraUpdateConverter..ctor() is inaccessible from method

**Comment by stavroaudi** [comment] 2018-07-31 10:32
On iOS I also get the error 'Attempting to JIT compile method 
'Xamarin.Forms.GoogleMaps.iOS.MapRenderer:UpdateMapType ()' while running in aot-only mode

**Comment by stavroaudi** [comment] 2018-07-31 14:01
I have the following: 

`        public void AddPinsTest(double latitude, double longitude, string companyName, string streetname, string cityName, string zipCode, string build)
        {
            var pinTest = new Pin
            {
                Position = new Position(latitude, longitude),
                Label = companyName,
                Address = streetname + " " + cityName + " " + zipCode + build,
            };
            pinTest.Clicked += Pin_Clicked;
            PSMap.ClusteredPins.Add(pinTest);

        }`

But since I changed from PSMap.Pins.Add(pinTest) to ClusteredPins, when I tap on a pin, the pin dialog does not appear, and the pinTest.Clicked+=Pin_Clicked doesn't even get called. 


This is my Pin_Clicked method: 

`        private async void Pin_Clicked(object sender, EventArgs eventArgs)
        {
            selectedPin = sender as Pin;
            var result = await DisplayAlert(selectedPin?.Label, selectedPin?.Address, AppResources.Navigate, "OK");
            if (result == true)
            {
                await CrossExternalMaps.Current.NavigateTo(
                selectedPin.Label,
                selectedPin.Position.Latitude,
                selectedPin.Position.Longitude,
                NavigationType.Driving);
            }
        }`

**Comment by KevinAble** [comment] 2018-07-31 14:57
@stavroaudi    until Yahavs changes get implemented into this package or someone steps up and makes an  extension package the only real option I found, was to pull down the code for both packages, compare/integrate/debug then reference the project directly in my solution,   the problem you are seeing with the pin click,  I solved by modifying the LookUpPIN in the clusterlogic.cs to 
        Pin LookupPin(Marker marker)
        {
            return GetItems(Map).FirstOrDefault(outerItem => ReferenceEquals(outerItem.NativeObject, marker.UserData as ClusteredMarker));
        }

**Comment by stavroaudi** [comment] 2018-08-01 06:32
@KevinAble Thanks for your reply. Silly question but how do I pull the code for both packages? And how do I modify the clusterlogic.cs?

**Comment by stavroaudi** [comment] 2018-08-01 14:57
I pulled @amay077's latest solution and copied @YahavGB's cluster solution to it, but I'm having a problem with iOS ClusterLogic.cs 

'using GMCluster;' 
is not found and I cannot find the package GMCluster anywhere. 

In 'internal class 'ClusterLogic : DefaultPinLogic<ClusteredMarker, MapView>'
it says ClusterLogic does not implement inherited abstract member 'DefaultPinLogic<ClusteredMarker, MapView>.OnUpdateZIndex(Pin, ClusteredMarker)' 

I appreciate any help! Of course adding @YahavGB's solution to the latest Xamarin.Forms.GoogleMaps update would be even better!

**Comment by stavroaudi** [comment] 2018-08-01 16:08
Tried pulling @YahavGB's changes onto the latest Xamarin.Forms.GoogleMaps update, didn't work for me. If anyone can implement @YahavGB's changes into the package it would be great. I have dependency issues and cannot use @YahavGB's solution anymore, unless it is added to the latest package. I will happily donate to whoever does so!

**Comment by KevinAble** [comment] 2018-08-01 16:16
@stavroaudi   you need to install  the Xamarin.iOS.Maps.Utils  Nuget package to your Xamarin.forms.IOS.GoogleMaps.IOS  project   that should clear up most of your reference issues.   I should have sometime this weekend to make a branch with my changes

**Comment by stavroaudi** [comment] 2018-08-02 11:54
@KevinAble I did, my issues were with ClusterLogic.cs on Android. If you could make DLLs like @YahavGB did for the shared library, android and iOS but for 3.0.1, I would be grateful!

**Comment by stavroaudi** [comment] 2018-08-06 11:10
Can anyone please help with pin clicked!? I can't access ClusterLogic.cs on Android/iOS.

**Comment by mierzynskim** [comment] 2018-08-06 12:38
Hey all!
Here's how I integrated most recent code with @YahavGB implementation [https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps/tree/clustering](url). Obviously there's a lot to improve and test, but it's a good starting point. I changed sample project to work with clustering. I'd like to compare it with @KevinAble implementation and we can probably try to implement the extension together.

**Comment by stavroaudi** [comment] 2018-08-06 13:02
@mierzynskim Happy to hear you got it working! Would it be possible to send me the precompiled DLLs for your solution for iOS/Android/Shared? Similar to what @YahavGB did but you seem to have version 3.0+ so it would work for me. Thank you!

**Comment by mierzynskim** [comment] 2018-08-06 15:09
@stavroaudi Here's a folder with precompiled dlls https://drive.google.com/open?id=1WamukWgSSR4NKdev2Wz-o2OuDePADsNy.

**Comment by vishaljani23** [comment] 2018-08-07 06:59
I am not able to render map... Can anybody suggest...
![map](https://user-images.githubusercontent.com/28733340/43759667-937fbee4-9a3d-11e8-9545-ab3b84cf401d.JPG)

**Comment by stavroaudi** [comment] 2018-08-07 08:11
@mierzynskim It works! Thanks a lot!

@vishaljani23 Make sure you have Xamarin.FormsGoogleMaps.Init(this, bundle); in your MainActivity.cs and you include your API key in your manifest

**Comment by stavroaudi** [comment] 2018-08-07 11:12
Does anyone know how to change pin color when it is on focus? i.e. when a pin is clicked, change the color from red to blue, and when another pin is clicked, change the former pin back to red and the new pin to blue etc.

**Comment by espritm** [comment] 2018-08-13 14:39
@mierzynskim Thanks for your work.
Do you know why the cluster need a lot of time to display icons when there is more than 1000 pins in the cluster ?
For instance, if I show the map with 200 pins in the cluster, the map needs 1 or 2 seconds to display. But if I show the map with 1000 pins in the cluster, the map needs 15 or 20sec to display :'(

**Comment by leemarthers** [comment] 2018-08-14 14:29
@mierzynskim @espritm I too am seeing very slow performance on anything above 1000 pins or so.  So far only tested on Android, ill try iOS later today and report back.

**Comment by stavroaudi** [comment] 2018-08-15 20:17
It's very slow on Android. I have 1500+ pins. It's fine on iOS

**Comment by leemarthers** [comment] 2018-08-17 19:58
@stavroaudi I am seeing the same thing.  everything works great on iOS but has very bad performance on android.

**Comment by rohitvipin** [comment] 2018-08-18 06:55
can we use https://github.com/streinhard/Xamarin.Google.iOS.Maps.Utility, so that project is also supported? we dont replicate effort at both places.

**Comment by leaguefun** [comment] 2018-08-18 06:58
Will it merge into the main repository? this is a great function of the library.

**Comment by mierzynskim** [comment] 2018-08-20 10:05
@espritm @leemarthers @stavroaudi I did a couple more tests and I agree it's too slow on Android 😞. Available algorithms use all markers to calculate clusters. That may cause bad performance. I updated android maps utils library and added `VisibleNonHierarchicalDistanceBasedAlgorithm` [(more info here)](https://github.com/googlemaps/android-maps-utils/pull/217) that operates only on a visible region. It slightly improved clustering speed for me. Please pull the latest changes from my fork and let me know if it helped.

**Comment by leemarthers** [comment] 2018-08-20 14:05
@mierzynskim thanks for looking into this.  I will test today.

**Comment by leemarthers** [comment] 2018-08-20 19:46
@mierzynskim The performance seems better with items under 10000 however it seems to be much worse (unusable) for somewhere around the 20k+ mark.  There seems to be an exponential slowdown as you increase the number.  30k never completed loading in my trials and crashed the emulator.  The slowdown occurs in the AddItems method.  It never completes with the 30k and as mentioned it slows to a crawl around the 20k mark.  Putting my simple code below:

`var rando = new Random();
            Map.ClusterOptions.Algorithm = ClusterAlgorithm.VisibleNonHierarchicalDistanceBased;           
            for (int i = 1; i <= 30000; i++)
            {
                var latitude = rando.NextDouble() * 180;
                var longitude = rando.NextDouble() * 180;
                var pin = new Pin() { Label = "test", Type = PinType.Place, Position = new Position(latitude, longitude) };
                Map.ClusteredPins.Add(pin);
               
            }`

**Comment by leemarthers** [comment] 2018-08-21 20:40
@mierzynskim, looks like we are running into a gref limit in android.

**Comment by stavroaudi** [comment] 2018-08-22 08:39
@mierzynskim Sorry I'm quite new to this. If I fork from your solution on visual studio, how can I create DLL files for Android and iOS? I know for the shared project I can make the solution as a nuget package. Otherwise if you can send me the precompiled DLLs that would be great. I can then test and let you know if there is a significant performance upgrade

**Comment by chrisgate** [comment] 2018-08-22 08:41
why dll when u have nuget https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/

**Comment by mierzynskim** [comment] 2018-08-22 14:21
@leemarthers Yeah, I think there's nothing more we can do with it 😞. For those of you who struggles with huge amount of markers [here's a possible solution.](https://stackoverflow.com/questions/26046253/how-to-use-viewport-marker-management-on-android). I haven't got time to test it myself but limiting amount of markers to a visible region seems to be good idea.

@amay077 I'd love to hear your thoughts about implementing the extension. I'm not sure what structure you expect but I offer my help to implement it.

**Comment by stavroaudi** [comment] 2018-08-23 17:44
@chrisgate The nuget doesn't include clustering.

**Comment by vishaljani23** [comment] 2018-08-28 18:38
@mierzynskim can you pls share latest compiled dlls for both Android and iOS... Thanks..

**Comment by carlosmacmar** [comment] 2018-08-29 15:48
Hey @mierzynskim ! I've been trying to check your clustering example but I'm not able to. There is an error in Xamarin.Forms.GoogleMaps.Android\Logics\ClusterLogic.cs. In this line:
`this.NativeMap.SetOnCameraIdleListener(this._clusterManager);`

I get the error:

> Argument 1: cannot convert from 'Com.Google.Maps.Android.Clustering.ClusterManager' to 'Android.Gms.Maps.GoogleMap.IOnCameraIdleListener' Xamarin.Forms.GoogleMaps.Android

Any idea about what could be happening? Thanks!!

**Comment by leemarthers** [comment] 2018-08-30 17:58
@mierzynskim I just noticed another issue in testing in android.  Each pin is being counted as two or three when clustered.  I have 37 pins but I am getting a bucket of 50+ and a bucket of 10+.  When I zoom in I can see a bucket of 6 break into 2 pins.  

Any thoughts?

**Comment by Ajin001** [comment] 2018-11-02 13:43
Latest Xamarin.Forms.GoogleMaps package not providing clustering feature in Xamarin forms.
Is there any alternative way to implement clustering in Xamarin form maps?
Thanks in Advance

**Comment by NamCkiku** [comment] 2018-11-28 06:09
I'm not set NativeObject  

            outerItem.NativeObject = marker;

**Comment by NamCkiku** [comment] 2018-11-29 10:03
I'm not update data pin marker when use ClursterPin. How to fix it?

**Comment by darkovuj** [comment] 2019-01-02 23:46
How to cluster less then 5 pins? If I change ClusterItemsCount to 3 in ClusterPage.xaml.cs (in XFGoogleMapSample) it does not cluster at all. Can you cluster less then 5 pins?

**Comment by darkovuj** [comment] 2019-01-02 23:59
I should ask this question 12h before, since I found solution 5sec after posting comment :(

answer is: set MinClusterSize in XamarinClusterRenderer.cs (Xamarin.Forms.GoogleMaps.Android.Logics.Cluster.XamarinClusterRenderer)
for example in ctor add: 
            this.MinClusterSize = 2;

**Comment by bryan2306** [comment] 2019-01-16 15:06
Bonjour , je souhaite faire sur ma map en UWP regrouper les icons lorsqu'ils sont tous au même en droit, cependant je n'ai trouver aucun code en c# qui me permet de m'aider a realiser cette tache 
pouvez vous m'aider svp après de nombreuses recherche cela ne me mène a rien 
je vous remercie

**Comment by gabrielbunselmeyer** [comment] 2019-01-31 16:09
Any more work being done on this? I think it's evident it'd be quite useful.

**Comment by mierzynskim** [comment] 2019-01-31 19:47
Hey! I finally had some time and created extension library for Xamarin.Forms.GoogleMaps https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering. It currently depends on my [custom fork](https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps) but I'm planning to create PR that introduces my changes to the core library and create a nuget package. So stayed tuned and I'd appreciate any feedback 😄

**Comment by gabrielbunselmeyer** [comment] 2019-01-31 19:49
That is some great work! Thanks so much.

**Comment by mierzynskim** [comment] 2019-01-31 20:11
and until there isn't official nuget package, you can find precompiled dlls here https://drive.google.com/open?id=1WamukWgSSR4NKdev2Wz-o2OuDePADsNy

**Comment by mierzynskim** [comment] 2019-02-06 18:28
@gabrielbunselmeyer I'm not sure if I got what you mean by that. Would you mind submitting an issue with more detailed explanation? Code samples would also be useful.

**Comment by gnout** [comment] 2019-02-07 08:06
@amay077 Are there any plans to integrate clustering to the GoogleMaps NuGet Package?

**Comment by NirmalSubedi17** [comment] 2019-02-08 17:01
@mierzynskim  If we do not set "Label" property of Pin. 
Map.PinClicked event always returns the First Clustered pin as PinClickedEventArgs. It will not return the one that was clicked.

**Comment by z-dmitri** [comment] 2019-02-09 18:45
@mierzynskim Amazing, Thanks a lot!
I found two things to fix, tested on Android - I sent you details already 
1. pins added on Map.CameraIdled event displayed only when user zoom map next time
> async void Map_OnCameraIdled(object sender, CameraIdledEventArgs e)
2. some time default pin icons displayed instead of one had been set, easy to reproduce:
> pin.Icon = BitmapDescriptorFactory.FromView(new MyPinView());

**Comment by NirmalSubedi17** [comment] 2019-02-12 17:27
@mierzynskim I faced Icon Changing issue. Icon is not changing when we assign new icon when somebody clicks on pin.
Here is the snippet:

```
map.PinClicked += (object sender, PinClickedEventArgs e) =>
            {
                if (e.Pin != null && e.Pin.Tag != null)
                {
                    if (activePin != null)
                        activePin.Icon = BitmapDescriptorFactory.FromBundle("mapRedPin");

                    var clickedPin = map.ClusteredPins.FirstOrDefault(f => f.Tag.Equals(e.Pin.Tag));
                    clickedPin.Icon= BitmapDescriptorFactory.FromBundle("mapBluePin");
                    activePin = clickedPin;
                }
            };
```
I tried same with E.Pin as well with no luck then I tried to Find the Pin from ClusteredPins.

Thank you,
Nirmal Subedi

**Comment by mierzynskim** [comment] 2019-02-12 18:01
@NirmalSubedi17 Thanks for pointing it out. Since Clustering became standalone repo, please create an issue on https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering. **Please also note that I'm not going to answer questions regarding issues in this thread anymore.**

**Comment by amay077** [comment] 2019-03-30 09:42
I support @NirmalSubedi17 's Xamarin.Forms.GoogleMaps.Clustering. (https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/123#issuecomment-462867320)

I don't add marker clustering in Xamarin.Forms.GoogleMaps.
If you want marker clustering, please use Xamarin.Forms.GoogleMaps.Clustering or you implement it.

**Closed by amay077** 2019-03-30 09:42 UTC
Labels: enhancement, help wanted

**Comment by AlonRom** [comment] 2020-12-01 07:58
> @amay077 as promised, I've implemented a unified API for clustering (a basic one, though).
> The API supports marker clustering, custom markers, custom clusters and buckets. It currently works on iOS and Android.
> 
> Please check my forked repository and check it so I can submit a pull request - https://github.com/YahavGB/Xamarin.Forms.GoogleMaps.
> 
> Sample code:
> 
> ```
>         for (var i = 0; i <= ClusterItemsCount; i++)
>         {
>             var lat = this._currentPosition.Latitude + Extent * GetRandomNumber(-1.0, 1.0);
>             var lng = this._currentPosition.Longitude + Extent * GetRandomNumber(-1.0, 1.0);
> 
>             this.Map.ClusteredPins.Add(new Pin()
>             {
>                 Position = new Position(lat, lng),
>                 Label = $"Item {i}",
>                 Icon = BitmapDescriptorFactory.FromBundle("pin_red.png")
>             });
>         }
> ```
> 
> Note the usage of ClusteredPins instead of Pins. Using that approach one can mix between standard pins (which won't be clustered) and clustered pins. For advance options, see ClusterOptions.cs.
> 
> Hope it'll help 👍 !

@YahavGB is there a way to distinguish between binding to the clustered itemsource and the regular pins itemsource without overriding the Xamarin.Forms.GoogleMaps source code?
