### ISSUE TITLE
Camera not getting updating on location change ios

### ISSUE THREAD

**Issue by sandyr39** [amay077/Xamarin.Forms.GoogleMaps#147] opened 2016-12-07 06:56 UTC
When the location changes, the camera view doesn't change.

**Comment by deextercz** [comment] 2017-01-04 20:30
Could you try it with latest pre-release?

**Comment by amay077** [comment] 2017-01-15 13:56
This is no longer response.
Could you provide more information for reproduce?

**Comment by amay077** [comment] 2017-01-24 17:09
I closed it because no longer response.

**Closed by amay077** 2017-01-24 17:09 UTC
