### ISSUE TITLE
best way to size custom pins

### ISSUE THREAD

**Issue by kitkat14** [amay077/Xamarin.Forms.GoogleMaps#59] opened 2016-08-14 11:30 UTC
What is the best way to show image size for pins in cross development ?

scale or create all kind of images with different size ? Anyone has some example for me...

**Comment by amay077** [comment] 2016-08-14 16:58
See #40 Why custom pin icon in iOS bigger than Android? 
I don't understand size calculation mechanism via BitmapDescriptorFactory.FromStream.

Workaround is using ``BitmapDescriptorFactory.FromBundle("image01.png")``.
In this case, you can prepare ``image01.png`` each platform.

For more information, please see [Custom marker support(v1.4.0-) - Comparison with Xamarin.Forms.Maps · amay077/Xamarin.Forms.GoogleMaps Wiki](https://github.com/amay077/Xamarin.Forms.GoogleMaps/wiki/Comparison-with-Xamarin.Forms.Maps#custom-marker-supportv140-)

**Comment by kitkat14** [comment] 2016-08-31 18:52
is there a way to use the resources instead of the assets for android ? that way you can use it for different screen sizes (hdpi/xhdpi and so on)

**Comment by amay077** [comment] 2016-09-30 16:59
I close this issue because this is duplicate of #40.
Please check #40 after this.

**Closed by amay077** 2016-09-30 16:59 UTC
Labels: discussion, duplicate
