### ISSUE TITLE
[Android]Support Google Play services 42+

### ISSUE THREAD

**Issue by adamhill** [amay077/Xamarin.Forms.GoogleMaps#239] opened 2017-02-16 17:51 UTC
Can we safely upgrade GoogleMaps.iOS and GooglePlay to the latest version for their respective Map controls?

**Comment by amay077** [comment] 2017-02-20 11:00
Sorry for late.

First, We should wait until made binding library by Xamarin when native Map control updated.

## Android Side

Xamarin.Forms.GoogleMaps is depend on [Xamarin Google Play Services - Maps](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Maps/).
The latest stable play services is version **42.1001.0**.
But we can not upgrade to it.
The reason is Xamarin.Forms dependencies.
The latest stable Xamarin.Forms is version **2.3.3.180**, 
And it **ONLY** depends Google play services **29.0.0.2** series.

## iOS Side

iOS side is simple.
We can just update [Google APIs Maps iOS Library](https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/) to new.

**Comment by dhaligas** [comment] 2017-03-01 17:44
2.3.3.193 supports upgrading.  Does your lib support the latest GPS?

**Comment by amay077** [comment] 2017-03-01 18:37
Sure!
It's a exciting announcement.
I have a plan to upgrade to new play services packages.

**Comment by dhaligas** [comment] 2017-03-01 19:42
thanks b/c the current Forms.Maps breaks when you try to upgrade.   they are not handling this

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/Extensions/MapViewExtensions.cs#L11

**Comment by jucaripo** [comment] 2017-03-03 23:24
amay077  time to release  Upgrade to GPS version 42.1001.0

**Comment by APinheiroPT** [comment] 2017-03-25 15:11
Amay077 For what date do you plan to integrate Google Play Service version 42.1001.0? 

Thanks for your work

**Comment by amay077** [comment] 2017-05-19 15:20
I just released [Xamarin.Forms.GoogleMaps 2.0.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.0.0-beta1).
This includes Xamarin.Forms 2.3.4+ and Xamarin.GooglePlayservices.Maps 42+ supports.
Could you try it?

**Comment by rizaanlakay** [comment] 2017-05-22 18:14
Adding the new GoogleMaps 2.0.0-beta1 causes an error "java.exe" exited with code 2

**Comment by APinheiroPT** [comment] 2017-05-22 19:13
I think the problem is because Xamarin.GooglePlayservices.Maps 42+ libraries, not GoogleMaps2.0.0. You need to activate Multidex on your app to compilate properly.

This problem is derived from a java limitation: https://medium.com/@rotxed/dex-skys-the-limit-no-65k-methods-is-28e6cb40cf71

**Comment by rizaanlakay** [comment] 2017-05-22 19:31
![capture](https://cloud.githubusercontent.com/assets/16114274/26325048/a7777914-3f35-11e7-9dbe-c82bd70397bc.JPG)

Here is what I did: 

- Removed 1.8 of GoogleMaps
- Removed all of GooglePlayServices 29.##.##
- Cleaned Solution
- Added 2.0.0.beta-1 to all the projects.
- Enabled Multidex in Android.

Same error. "Java.exe" exited with code 2.

**Comment by amay077** [comment] 2017-05-22 22:23
According this post - https://forums.xamarin.com/discussion/comment/239913/#Comment_239913 , 
You should use Java1.8 and update proguard.
Please check it.

**Comment by APinheiroPT** [comment] 2017-05-23 09:24
Yes java 1.8 and update proguard is nedeed... But what is your version of visual studio? 

If you are using the last version of visual studio, this have a bug related to multidex checkbox:

Bug 56192 [Xamarin.VisualStudio] MultiDex is disabled after saving changes to Xamarin.Android project due to incorrect MSBuild property name <AndroidEnableMultipleDex>. Now RESOLVED in the source code, and will be included in an upcoming release.
Workaround: In the .csproj file, replace all occurrences of AndroidEnableMultipleDex with the correct property name AndroidEnableMultiDex using a text editor.

You can see this and other bugs of current version of VS here: https://releases.xamarin.com/common-issues-from-the-xamarin-15-2-release-being-tracked-by-the-xamarin-team/

**Comment by amay077** [comment] 2017-06-07 13:49
You can use [Xamarin.Forms.GoogleMaps 2.0.0+](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.0.0).

**Closed by amay077** 2017-06-07 13:49 UTC
Labels: enhancement, in review
