### ISSUE TITLE
Show user location and custom Pin are not working in UWP

### ISSUE THREAD

**Issue by sarathiu** [amay077/Xamarin.Forms.GoogleMaps#115] opened 2016-11-21 12:57 UTC
1. I have implemented the Xamarin.Forms.GoogleMaps for Cross Platform Project.
If I enable the  IsShowingUser = true in UWP, Then I got crash. I had following Issue details
(It works fine in Android)

Exception = {"Object reference not set to an instance of an object."}

at Xamarin.Forms.GoogleMaps.UWP.MapRenderer.LoadUserPosition(Geocoordinate userCoordinate, Boolean center) at Xamarin.Forms.GoogleMaps.UWP.MapRenderer.d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xamarin.Forms.GoogleMaps.UWP.MapRenderer.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state) at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

2. The **Custom Pin** option is not working in **UWP** project. I have used the same code for android it works.

kindly identify and fix these issues.

**Comment by deextercz** [comment] 2016-11-21 12:59
Could you please tell me which version of Xamarin.Forms.GoogleMaps do you use?
I will try it if I am able to induce.

**Comment by sarathiu** [comment] 2016-11-21 13:00
Xamarin.Forms.GoogleMaps 1.7.0

**Comment by deextercz** [comment] 2016-11-21 13:27
For me it works, try to use beta version 4
Custom pins for UWP is not implemented I want to implement it, but I dont know how right now.

**Comment by sarathiu** [comment] 2016-11-21 13:38
Thanks for your suggestion, Still the issue exist.

![image](https://cloud.githubusercontent.com/assets/13977806/20484600/e0c22d7e-b01d-11e6-9d26-d261e7751eaf.png)

**Comment by amay077** [comment] 2016-12-07 16:26
> @JKennedy24 ,

Could you reproduce (and fix) it?
(Sorry I don't have real windows phone device.)

**Comment by JKennedy24** [comment] 2016-12-07 16:34
When trying to use UserLocation I get:

Access is denied.
Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.

I will try have a look into this when I can.

@amay077  I dont have windows phone either I am using UWP application on Windows 10, works quite well

Custom pushpins have been submitted as a pull request here: https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/143

**Comment by amay077** [comment] 2017-01-16 14:16
I added "location" to device capability in UWP Sample app.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/8a2373dd3982a472d91f87f117fea5a080df96ef

This is works fine in my Win10 desktop.
Can I close this?

**Comment by amay077** [comment] 2017-01-23 08:25
I close it because no longer response.

**Closed by amay077** 2017-01-23 08:25 UTC
