### ISSUE TITLE
BitmapDescriptorFactory.FromBundle does not work on Android

### ISSUE THREAD

**Issue by FWJay** [amay077/Xamarin.Forms.GoogleMaps#169] opened 2017-01-09 13:07 UTC
```
Map.Pins.Add(mappin);
Map.InfoWindowClicked += async (sender, e) =>
                               {
                                   if (!IsNavigating)
                                   {
                                       IsNavigating = true;
                                       await Navigation.PushAsync(new Details());
                                   }
                               };
```

The above code seems to crash on Android! has anybody experienced this?

**Comment by deextercz** [comment] 2017-01-09 13:09
Could post also stack trace?
po 9. 1. 2017 v 14:07 odesílatel Jay Kannan (FW) <notifications@github.com>
napsal:

**Comment by FWJay** [comment] 2017-01-09 13:21
here's one
<img width="2190" alt="screen_shot_2017-01-09_at_3 32 14_pm" src="https://cloud.githubusercontent.com/assets/555988/21767907/91cfc6dc-d66e-11e6-9dfc-7c632cbf6409.png">

**Comment by amay077** [comment] 2017-01-10 06:02
Is this something related to the Xamarin.Forms.GoogleMaps?
Could you try navigate to ``Detail`` page with simply ``button.Clicked`` event.

**Comment by FWJay** [comment] 2017-01-10 10:11
yes it is, I commented them out and it doesn't crash. adding custom pins seems to crash the android build. could you suggest where I can look deeper as I cannot share much of the code without permission?

**Comment by FWJay** [comment] 2017-01-13 10:44
no comments? has everybody got InfoWindow + Pin icons working on Android?

**Comment by amay077** [comment] 2017-01-13 11:51
I can not reproduce it.

I added navigate to DetailPage when Pin's InfoWindows clicked in [XFGoogleMapSample at issue_169 branch](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/issue_169/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L125).

![untitled](https://cloud.githubusercontent.com/assets/401369/21929054/bfed00aa-d9d1-11e6-84ac-bb386390a155.gif)

**Comment by FWJay** [comment] 2017-01-13 16:50
thanks, maybe I'm doing something wrong! thanks. what build should I be using?

**Comment by amay077** [comment] 2017-01-15 13:34
Does set ``map_pincustom.png``'s build action to "AndroidAsset"?

![2017-01-15 22 28 07](https://cloud.githubusercontent.com/assets/401369/21962829/203a9160-db72-11e6-8910-8922af37c406.png)

**Comment by FWJay** [comment] 2017-01-16 15:25
Let me check and report!

**Comment by amay077** [comment] 2017-04-11 05:06
No longer any comments, so close this issue.
Please re-open if you needed.

**Closed by amay077** 2017-04-11 05:06 UTC

**Comment by andresgutice** [comment] 2017-08-07 06:27
Thanks, it was helpful for me...

**Comment by alexeystrakh** [comment] 2018-01-28 05:38
Same issue here, BitmapDescriptorFactory.FromBundle("my_custom_image") crashes the app on Android and works fine for iOS. 

I'm using the latest 2.3 Xamarin.Forms.GoogleMaps and creating custom pin using similar code.

It doesn't work even if I add an image as android asset.

**Comment by amay077** [comment] 2018-01-29 14:28
Hi @alexeystrakh ,

Yes, we don't support Android Drawables because difficult to keep API compatibility with iOS.
see - https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/347 

But I have an idea for support it - https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/436 .
If you are interested in it then please any comment or post ":+1:" in #436 .

**Comment by AmorimRob** [comment] 2018-02-19 22:05
Change to AndroidAsset works for me, Thanks! It was helpful
