### ISSUE TITLE
[Android] Map.Pins.Remove and Map.Pins.Clear don't work

### ISSUE THREAD

**Issue by AntonAndr** [amay077/Xamarin.Forms.GoogleMaps#55] opened 2016-08-10 10:05 UTC
[Android] Map.Pins.Remove doesn't remove pin from map.
[Android] Map.Pins.Clear works once for map, then doesn't remove pins.
Removed pins don't exist in Map.Pins collection but still displaying on map.

Actual for both 1.5.0 and 1.5.1

**Comment by amay077** [comment] 2016-08-10 11:06
Can you reproduce in XFGoogleMapSample?

**Comment by AntonAndr** [comment] 2016-08-10 12:16
I will try and report result

**Comment by AntonAndr** [comment] 2016-08-12 11:11
Same bug with Map.Pins.Clear in XFGoogleMapSample. Map.Pins.Remove works

packages: Xamarin.Forms 2.3.1.114, Xamarin.Forms.GoogleMaps 1.5.0/1.5.1, Xamarin.GooglePlayServices.Maps 29.0.0.2

devices: Sony Xperia P (Android 4.1.2), Samsung Galaxy Tab 3 Lite (Android 4.2.2), Samsung Galaxy S4 Mini (Android 4.4)

**Comment by amay077** [comment] 2016-08-14 17:19
Thanks for information.
But I can't reproduce this.

I captured my steps via [Vysor](http://www.vysor.io/), Is it right about my steps?
This looks like it is working correctly.

![untitled2](https://cloud.githubusercontent.com/assets/401369/17650657/c85b11fc-628d-11e6-90a7-c1e2692a7018.gif)

devices: Sony Xperia Z3 compact, Samsung Galaxy S5, Google Nexus 9

**Comment by amay077** [comment] 2016-09-30 16:54
There is no longer a response.
I close this issue but if you want help then post comment.

**Comment by yasmeenshourasoft** [comment] 2017-04-02 10:31
i use this to remove pin in xamarin forms application
            Device.BeginInvokeOnMainThread(() =>
            {
                    for (int x = 0; x < customMap.Pins.Count; x++)
                    { customMap.Pins.RemoveAt(x); }//.Remove(customMap.Pins[x]); }
                    for (int x = 0; x < customMap.CustomPins.Count; x++)
                    { customMap.CustomPins.RemoveAt(x); }//.Remove(customMap.CustomPins[x]); }
                }
            });
and use this 
 customMap.Pins.clear();
 customMap.CustomPins.clear();
it  work good in ios only but in android it doesn't delete pin.....
what it is the problem??
can  you advice me?

**Comment by deextercz** [comment] 2017-04-02 18:31
I think problem is in Device.BeginInvoke... could you it without this on UI thread?

**Comment by yasmeenshourasoft** [comment] 2017-04-02 18:49
I try without it but didn't  work
بتاريخ ٠٢‏/٠٤‏/٢٠١٧ ٨:٣١ م، جاء من "deextercz" <notifications@github.com>:

**Comment by deextercz** [comment] 2017-04-02 19:00
Are xou able to reproduce that with sample solution? If not it looks like problem isnin custompin

**Comment by yasmeenshourasoft** [comment] 2017-04-02 19:05
I use this example
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/map/customized-pin/
And update  it to add more pins and remove  this when user do action
But they didn't remove
بتاريخ ٠٢‏/٠٤‏/٢٠١٧ ٩:٠٠ م، جاء من "deextercz" <notifications@github.com>:

**Comment by yasmeenshourasoft** [comment] 2017-04-03 05:52
can you share your sample that you develop above ??

**Comment by yasmeenshourasoft** [comment] 2017-04-03 07:38
https://drive.google.com/file/d/0B6kqP-UpSCqec2tmREExbFRUT3M/view?usp=sharing
this is my app ,i can't remove pins

**Comment by amay077** [comment] 2017-04-11 05:04
Similar to #259

**Comment by cacaxiq** [comment] 2017-11-20 18:20
Hello guys,


I'm having the same problem with the presentation of the pins. Some differences from the test example are that many pins are displayed and they have custom images using BitmapDescriptorFactory.FromBundle (icone).

Could you help us.

**Comment by cacaxiq** [comment] 2017-11-20 20:11
Hello guys 

Meu problema foi resolvido ao definir a propriedade Endereço no objecto do Pin. Anteriormente ela ficava como empty.

**Comment by amay077** [comment] 2018-06-21 10:50
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!

**Closed by amay077** 2018-06-21 10:50 UTC
